---
title: "Thesis"
author: "Lars Wenger"
date: "2024-02-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r install}
# We start by installing the necessary libraries. Make sure to uncomment and run
# only the libraries which you haven't installed already. 
#install.packages("DescTools")
#install.packages("xgboost")
#install.packages("caret")
#install.packages("dplyr")
#install.packages("tidyverse")
#install.packages("mltools")
#install.packages("reshape2")
#install.packages("data.table")
#install.packages("pracma")
#install.packages("rsample")
# install.packages("PRROC")
# install.packages("e1071")
# install.packages("dlookr")
# install.packages("pROC")
# install.packages("ROCR")
# install.packages("nnet")
```
```{r libraries}
library(DescTools)
library(xgboost)
library(caret)
library(dplyr)
library(tidyverse)
library(mltools)
library(reshape2)
library(data.table)
library(pracma)
library(rsample)
library(PRROC)
library(e1071)
library(dlookr)
library(pROC)
library(ROCR)
library(nnet)
library(ggplot2)
#library POSIXct
library(lubridate)
options(scipen=999)
```


```{r import}
## Import data
# We set the working directory and we call the data that we are going to use. Please import the csv file.
rm(list=ls())

set.seed(7)

setwd("C:/Thesis")
#read json file
cases_data <- read_csv("Data/sn_customerservice_case.csv", locale = locale(encoding = "UTF-8"))
data <- cases_data # We make a copy from the original dataset and work on the copy

```

```{r}
# show the column comments
cases_data %>% 
  select(comments_and_work_notes) %>% 
  head(10)

# Split the comments column into multiple columns. Split all the comments by the character "mm-dd-YYY HH:MM:SS - " and create a new column for each part of the comment
# Example string


# Split the string using a regex pattern
# The pattern \d{2}-\d{2}-\d{4} \d{2}:\d{2}:\d{2} - matches the date and time format
split_text <- strsplit(cases_data$comments_and_work_notes[202], split = "\\d{2}-\\d{2}-\\d{4} \\d{2}:\\d{2}:\\d{2} -", perl = TRUE)

# View the result
print(cases_data$comments_and_work_notes[202])
print(split_text)
print(cases_data$number[202])

```

```{r strucutre}
data <- select(cases_data, number = number, case = short_description, description = description, case_type = u_case_type, first_response_time = first_response_time, closed = closed_at, opened = opened_at, account = account, created_by = sys_created_by, business_service = business_service, assigned_to = assigned_to, assignment_group = assignment_group, auto_close = auto_close, time_worked = u_total_time_worked, reassignment_count = reassignment_count, impact = impact, priority = priority, urgency = urgency, comments = comments_and_work_notes, case_cause = u_case_cause, cause = cause, close_notes = close_notes, resolution_code = resolution_code)

```

```{r data}
# Filter between dates and removing rows who are not closed
data <- data %>% 
  filter(Year(strptime(data$opened, "%d-%m-%Y %H:%M:%S", tz="UTC")) <= Year("2024-02-01")) %>%
  filter(Year(strptime(data$opened, "%d-%m-%Y %H:%M:%S", tz="UTC")) >= Year("2020-01-01")) %>%
  filter(!is.na(closed))
```

```{r type}
# Transforming the type of the variables
data$opened <- as.POSIXct(strptime(data$opened, "%d-%m-%Y %H:%M:%S", tz="UTC"))
data$closed <- as.POSIXct(strptime(data$closed, "%d-%m-%Y %H:%M:%S", tz="UTC"))
data$first_response_time <- as.POSIXct(strptime(data$first_response_time, "%d-%m-%Y %H:%M:%S", tz="UTC"))
data$auto_close <- as.factor(data$auto_close)
data$reassignment_count <- as.numeric(data$reassignment_count)
data$impact <- as.factor(data$impact)
data$priority <- as.factor(data$priority)
data$urgency <- as.factor(data$urgency)
data$case_cause <- as.factor(data$case_cause)
data$resolution_code <- as.factor(data$resolution_code)
data$assignment_group <- as.factor(data$assignment_group)
data$assigned_to <- as.factor(data$assigned_to)
data$created_by <- as.factor(data$created_by)
data$business_service <- as.factor(data$business_service)
data$case_type <- as.factor(data$case_type)
data$account <- as.factor(data$account)
data$openedToClosed <- as.numeric(difftime(data$closed, data$opened, units = "hours"))
# add column created by cleaned. When cretad_by is admin, then it is system, when created_by ends witch @unico.ch then it is unico, otherwise it is user
data$created_by_group <- as.factor(ifelse(data$created_by == "admin", "System", ifelse(grepl("@unico.ch", data$created_by), "Unico", "User")))
```

```{r merging-sla}
# merg data sets
sla_data_clean <- read_csv("Data/task_sla.csv")

# Remove all rows, where sla_data£status is Cancelled
# sla_data <- sla_data %>% 
#   filter(stage != "Cancelled")


# Merge data and sla_data, where the number and closed of data is the same as task and stop time of sla_data

sla_data <- select(sla_data_clean, task = task, business_percentage = business_percentage, sla_has_breached = has_breached, end_time = task.closed_at)

#remove duplicates of sla_data$task
sla_data <- sla_data %>% 
  distinct(task, .keep_all = TRUE)

sla_data$end_time <- as.POSIXct(strptime(sla_data$end_time, "%d-%m-%Y %H:%M:%S", tz="UTC"))

data <- merge(x = data, y = sla_data, 
                     by.x = c('number', 'closed'), 
                     by.y = c('task', 'end_time'), 
                     all.x = TRUE)

data$business_percentage <- as.numeric(data$business_percentage)
data$sla_has_breached <- as.factor(data$sla_has_breached)

```
```{r check}
# Take specific STRUCTUREED columns how are interesting and remove all NA's
data <- na.omit(select(data, number, account, created_by_group, business_service, assignment_group, auto_close, impact, priority, urgency, sla_has_breached, case_cause, resolution_code, reassignment_count, time_worked, opened, closed, openedToClosed, business_percentage))
```

```{r cleaning}
#Remove all rows, where account, Busienss Service and created_by is less than 100 time in the dataset
data <- data %>% group_by(account) %>% filter(n() > 100)
data <- data %>% group_by(business_service) %>% filter(n() > 100)
data <- data %>% group_by(assignment_group) %>% filter(n() > 20)
#Verzicht auf Case Type, da ich sowieso nur Troubles anschaue
#data <- data %>% filter(case_type == 'Trouble')
```

```{r,echo=FALSE}
outlier <- function(x){
  quantiles <- quantile(x, c(.05, .95))
  x[x < quantiles[1]] <- quantiles[1]
  x[x > quantiles[2]] <- quantiles[2]
  x
}   
```

In the next step, we apply the outlier function. For this, we use the map_df function. This allows us to apply a function to each element of a list or atomic vector.

```{r, echo=FALSE}

#Use function outlier for the dataset
# data['reassignment_count'] <- map_df(data['reassignment_count'], outlier)
# data['time_worked'] <- map_df(data['time_worked'], outlier)
# data['openedToClosed'] <- map_df(data['openedToClosed'], outlier)
# data['business_percentage'] <- map_df(data['business_percentage'], outlier)
```

```{r}
# data_new <- merge(data, cases_data[c('sys_id','number','description', 'cause', 'close_notes')], by = "number", all.x = FALSE)
data <- merge(data, cases_data[c('number','description', 'cause', 'close_notes')], by = "number", all.x = FALSE)
```

```{r save}
# Save the data
write.csv(data, "Data/data.csv",row.names = FALSE)
```
