---
title: "Thesis - Clustering"
author: "Lars Wenger"
date: "2024-02-14"
output: html_document
---

DO THE code_clustering befor run this code!

```{r}
# K-means Clustering
set.seed(72) 
k <- 3
kmeans_model <- kmeans(encoded_df, centers = k)

elbow_data <- data.frame(
  k = 1:15,
  total_withinss = numeric(15)
)

for(i in 1:15) {
  set.seed(123456)
  km <- kmeans(encoded_df, centers = i)
  elbow_data[i, "total_withinss"] <- km$tot.withinss
}

ggplot(elbow_data, aes(x = k, y = total_withinss)) + 
  geom_line() + 
  geom_point() + 
  scale_x_continuous(breaks = seq(1, 15, 1)) +
  labs(title = "Elbow Method", x = "Number of Clusters", 
       y = "Total Within-Cluster Sum of Squares") +
  theme_minimal()
```

```{r, k-mean, message=FALSE}
k <- 8
set.seed(123456)
kmeans_model <- kmeans(encoded_df, centers = k)

pca_fit <- PCA(encoded_df, graph = FALSE)
pc1 <- pca_fit$ind$coord[, 1]
pc2 <- pca_fit$ind$coord[, 2]

cluster_data <- data.frame(cluster = as.factor(kmeans_model$cluster), pc1, pc2)

data$cluster <- as.factor(kmeans_model$cluster) 
table(data$cluster) 
data_subset <- data %>% 
  group_by(cluster) %>%
  slice_head(n = 2) %>% 
  ungroup()

```


```{r hirachical single}
k = 8
# Hierarchical clustering with single linkage
hier_data1_single <- hclust(dist(encoded_df), method = "single")
clusters_data1_single <- cutree(hier_data1_single, k = k)

cluster_data <- data.frame(number = data$number, cluster = clusters_data1_single)

# Merge the cluster information back to the original data
final_data <- merge(cases_data, cluster_data, by = "number", all.x = TRUE)

# Count the number of stocks in each cluster 
table(final_data$cluster) 
#Median of openedToClosed as number
summary(final_data[final_data$cluster == c(1,2,3,4,5,6,8),])
#summary me the distibution of the cluster 7
summary(final_data[final_data$cluster == 7,])
```

```{r hirachical complete}
k =11
# Hierarchical clustering with complete linkage
hier_data1_comp <- hclust(dist(encoded_df), method = "complete")
clusters_data1_comp <- cutree(hier_data1_comp, k = k)

# If encoded_df doesn't already include the number, you'll need to ensure it's correctly aligned with original data
cluster_data <- data.frame(number = data$number, cluster = clusters_data1_comp)

# Merge the cluster information back to the original data
final_data <- merge(cases_data, cluster_data, by = "number", all.x = TRUE)

# Count the number of stocks in each cluster 
table(final_data$cluster) 

#Median of openedToClosed as number
summary(final_data[final_data$cluster == c(1,2,3,4,5,6,7),])
#summary me the distibution of the cluster 7
summary(final_data[final_data$cluster == 8,])
```

```{r analyzeCluster}
# Assuming 'data' is your dataset and 'cluster' is the column indicating cluster membership
final_data$cluster <- as.factor(final_data$cluster) # Ensure the cluster variable is a factor

# Summary statistics for each cluster
summary_stats <- final_data %>%
  group_by(cluster) %>%
  summarise_all(funs(mean = mean(., na.rm = TRUE), sd = sd(., na.rm = TRUE)))

# Boxplots for a variable across clusters
ggplot(final_data, aes(x = cluster, y = final_data$openedToClosed)) + 
  geom_boxplot() +
  theme_minimal() +
  labs(title = "Distribution of Opened to Closed Across Clusters", y = "Opened to Closed (Hours)", x = "Cluster")


```
