---
title: "History Line"
author: "Lars Wenger"
date: "2024-03-26"
output: html_document
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      results = "hide")
```

# Import Libraries
```{r echo = T, results = 'hide'}
libraries <- c("fpp3", "ggplot2", "dplyr", "tidyr", "readxl", "forecast", "zoo", "tsibble", "GGally", "lubridate", "tidyverse", "stringi")

# Install any missing libraries
lapply(libraries, function(x) if (!(x %in% installed.packages())) {
  install.packages(x)
})

# Load libraries
lapply(libraries, library, quietly = TRUE, character.only = TRUE)
```

# Read Data
```{r read_data}
# Clear the workspace
rm(list=ls())

# Set working directory
setwd("C:/Thesis")

# Read system history data
history_data <- read_csv("Data/sys_history_line.csv", locale = locale(encoding = "UTF-8"))

# Ensure 'update_time' has seconds, convert to POSIXct
history_data$update_time <- ifelse(nchar(history_data$update_time) == 16, paste0(history_data$update_time, ":00"), history_data$update_time)
history_data$update_time <- as.POSIXct(strptime(history_data$update_time, "%d.%m.%Y %H:%M:%S", tz="UTC"))

# Select relevant columns
history_data <- select(history_data, set, update_time, field, old, new)

# Read main data
data_all <- read_csv("Data/data.csv", locale = locale(encoding = "UTF-8"))

# Merge history data with main data on 'set' and 'number'
data <- history_data %>%
  mutate(set = trimws(gsub("Case:", " ", set))) %>%
  inner_join(select(data_all, number, account, opened, closed, openedToClosed), by = c("set" = "number"))
```

# Data Processing

```{r}
# Count unique 'set' numbers
unique_sets <- data %>%
  count(set) %>%
  nrow()
print(unique_sets)

# Plot the frequency of each category in 'field'
history_data %>%
  count(field) %>%
  ggplot(aes(x = fct_reorder(field, n), y = n)) +
  geom_col() +
  coord_flip() +
  labs(title = "Frequency of each category in 'field'")

# Plot the frequency of each 'old' state when 'field' is 'state'
history_data %>%
  filter(field == "state") %>%
  count(old) %>%
  ggplot(aes(x = fct_reorder(old, n), y = n)) +
  geom_col() +
  coord_flip() +
  labs(title = "Frequency of each category in 'old' for 'state' field")

# Plot the frequency of each 'old' assignment group when 'field' is 'assignment_group'
history_data %>%
  filter(field == "assignment_group") %>%
  count(old) %>%
  ggplot(aes(x = fct_reorder(old, n), y = n)) +
  geom_col() +
  coord_flip() +
  labs(title = "Frequency of each category in 'old' for 'assignment_group' field")


```
# Data Cleaning and Transformation


```{r data_processing}
# Translate 'old' values from German to English
data <- data %>%
  mutate(old = ifelse(old == "Offen", "Open", old)) %>%
  mutate(old = ifelse(old == "Geschlossen", "Closed", old)) %>%
  mutate(old = ifelse(old == "In Bearbeitung", "Work in Progress", old)) %>%
  mutate(old = ifelse(old == "Wartend", "On hold", old)) %>%
  mutate(old = ifelse(old == "Gelöst", "Resolved", old))

# Filter out records where 'update_time' is after 'closed' but 'new' is not "Closed"
data <- data %>%
  filter(!(update_time > closed + hours(2) & new != "Closed"))

# Replace 'old' with 'new' if only one change was made on a field
replace_condition <- with(data, ave(seq_along(set), set, field, FUN = length) == 1)
data$old[replace_condition] <- data$new[replace_condition]
```

# Assignment Group Processing

```{r}
# Function to process assignment groups and replace infrequent groups with "Other"
process_assignment_groups <- function(df, fieldName, number) {
  filtered_data <- df %>%
    filter(field == fieldName) %>%
    filter(!is.na(old))
  
  top_groups <- filtered_data %>%
    count(old) %>%
    arrange(desc(n)) %>%
    slice_head(n = number) %>%
    pull(old)
  
  df <- df %>%
    mutate(old = ifelse(field == fieldName & old %in% top_groups, old, ifelse(field == fieldName, "Other", old)))
  
  return(df)
}

data <- process_assignment_groups(data, fieldName = "assignment_group", number = 6)
```

# Time Difference Calculation

```{r}
# Calculate time differences from 'opened' to 'update_time'
data <- data %>%
  mutate(time_diff_opened = as.numeric(update_time - opened))

# Function to calculate time differences for different fields
calculate_time_diff <- function(data, field_name) {
  data %>%
    filter(field == field_name) %>%
    arrange(update_time) %>%
    group_by(set) %>%
    mutate(
      time_diff_previous = as.numeric(difftime(update_time, lag(update_time, default = first(opened)), units = "hours")),
      sum_time_diff = sum(time_diff_previous, na.rm = TRUE),
      percentage_time_diff = ifelse(is.na(time_diff_previous) & n() == 1, 100, time_diff_previous / sum_time_diff * 100)
    ) %>%
    filter(!is.na(old)) %>%
    select(set, old, percentage_time_diff) %>%
    ungroup()
}

# Apply the function for different fields
data_state <- calculate_time_diff(data, "state")
data_assignment_group <- calculate_time_diff(data, "assignment_group")

```

# Encoding

```{r encoding}
# One-hot encode specified columns
one_hot_encode <- function(df, columns) {
  if(!is.character(columns)) stop("columns argument must be a character vector specifying column names to encode")
  if(!all(columns %in% names(df))) stop("Not all specified columns exist in the dataframe")
  
  result_df <- df[, !(names(df) %in% columns)]
  
  for(column in columns) {
    temp_df <- data.frame(df[[column]], stringsAsFactors = FALSE)
    colnames(temp_df) <- column
    
    encoded_matrix <- model.matrix(~ . - 1, data = temp_df)
    encoded_df <- data.frame(encoded_matrix)
    
    colnames(encoded_df) <- gsub("X", column, colnames(encoded_df))
    
    result_df <- cbind(result_df, encoded_df)
  }
  
  return(cbind(df[1], result_df))
}

# Apply one-hot encoding to different fields
encoded_df_state <- one_hot_encode(data_state, "old")
encoded_df_assignment_group <- one_hot_encode(data_assignment_group, "old")
```

# Aggregation

```{r aggregation}
# Remove unnecessary columns and replace values with percentages
encoded_df_state <- encoded_df_state[-2]
encoded_df_assignment_group <- encoded_df_assignment_group[-2]

replace_with_percentage <- function(df, percentage_col) {
  df[, -c(1, 2)] <- df[, -c(1, 2)] * df[, percentage_col]
  df[, -1] <- round(df[, -1], 2)
  return(df)
}

encoded_df_state <- replace_with_percentage(encoded_df_state, "percentage_time_diff")
encoded_df_assignment_group <- replace_with_percentage(encoded_df_assignment_group, "percentage_time_diff")

# Summarize grouped dataframes
summarize_grouped_df <- function(df) {
  df %>%
    group_by(set) %>%
    summarise(across(-1, sum, na.rm = TRUE)) %>%
    ungroup()
}

grouped_encoded_df_state <- summarize_grouped_df(encoded_df_state)
grouped_encoded_df_assignment_group <- summarize_grouped_df(encoded_df_assignment_group)

# Replace column names
replace_column_names <- function(df, prefix) {
  colnames(df) <- gsub("old", prefix, colnames(df))
  return(df)
}

grouped_encoded_df_state <- replace_column_names(grouped_encoded_df_state, "prop_state_")
grouped_encoded_df_assignment_group <- replace_column_names(grouped_encoded_df_assignment_group, "prop_group_")
```

# Merge Dataframes

```{r merge_dataframes}
# Merge all dataframes
final_df <- Reduce(function(x, y) merge(x, y, by = "set", all = TRUE), 
                   list(grouped_encoded_df_state, grouped_encoded_df_assignment_group))

# Rename 'set' to 'number'
colnames(final_df)[1] <- "number"
```

# Save Data
```{r save_data}
# Save the final dataframe
# rename column prop_state_On.hprop_state_ to prop_state_On.hold
colnames(final_df)[4] <- "prop_state_On.hold"
write_csv(final_df, "Data/data_proportion.csv")
```
